FROM alpine:3.7

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update                                                                    && \
    apk add --no-cache build-base git bash linux-headers ca-certificates curl \
        openssh tzdata net-tools go glide godep
        
